# Generated by Django 4.1.2 on 2022-11-09 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_recipe_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='base.section'),
        ),
    ]
