# Generated by Django 4.1.2 on 2022-11-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_recipe_time_to_make"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="color",
            field=models.CharField(default="#ffffff", max_length=16),
        ),
    ]
