# Generated by Django 4.1.1 on 2022-11-14 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_delete_order_alter_recipe_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='base.section'),
        ),
    ]
