# Generated by Django 4.1.1 on 2022-11-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_recipe_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='section',
        ),
    ]
