# Generated by Django 4.1.2 on 2022-11-09 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_section_color"),
        ("base", "0008_remove_recipe_section"),
    ]

    operations = []
