<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-11-09 02:20
=======
# Generated by Django 4.1.2 on 2022-11-09 00:42
>>>>>>> eb1e449aaa0139022ff23c1a7c0c880447491da1

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_section_color"),
        ("base", "0008_remove_recipe_section"),
    ]

    operations = []
