# Generated by Django 4.1.2 on 2022-11-09 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_merge_0004_section_color_0008_remove_recipe_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="section",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="base.section",
            ),
        ),
    ]
