# Generated by Django 4.1.2 on 2022-11-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_recipe_name_alter_section_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='section',
            name='unique name for each user',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
