# Generated by Django 4.1.2 on 2022-11-09 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_recipe_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="base.section"
            ),
        ),
    ]
