# Generated by Django 4.1.2 on 2022-11-17 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_remove_section_unique name for each user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recipes",
                to="base.section",
            ),
        ),
    ]
