# Generated by Django 4.1.1 on 2022-11-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='section',
        ),
        migrations.AddField(
            model_name='recipe',
            name='section',
            field=models.ManyToManyField(blank=True, to='base.section'),
        ),
    ]
