# Generated by Django 4.1.2 on 2022-11-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_food_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_unit',
            field=models.BooleanField(default=True),
        ),
    ]
