# Generated by Django 4.1.2 on 2022-11-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_recipe_section'),
        ('base', '0017_recipe_time_unit'),
    ]

    operations = [
    ]
