# Generated by Django 4.1.2 on 2022-11-26 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_merge_0017_alter_recipe_section_0017_recipe_time_unit"),
    ]

    operations = [
        migrations.RemoveField(model_name="recipe", name="time_unit",),
    ]
