# Generated by Django 4.1.2 on 2022-11-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_remove_recipe_time_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="time_unit",
            field=models.CharField(
                choices=[("minutes", "MINUTES"), ("hours", "HOURS")],
                default="minutes",
                max_length=10,
            ),
        ),
    ]
